= Welcome to the modelix platform!
:navtitle: Introduction

== Introduction

The modelix project develops an open source platform for (meta-)models on the web.
We are native to the web and the cloud, inspired by xref:glossary.adoc#whitepaper[this whitepaper].
On the path to this final vision, we currently develop multiple components that implment parts of this vision.
Consequently, some parts are very stable and already in productive use while others are in a more experimental and explorative state.

Follow the 'Next' button in the bottom right to find out more details on architecture and components available, or dive directly xref:samples:index.adoc[into our samples] to get started!

Otherwise, the xref:faq.adoc[FAQ] section might give answers to some of your immediate questions.


== Glossary

In this documentation we use various acronyms and domain-specific wording.
Head over to the xref:glossary.adoc[Glossary] if you are unsure about what exactly we mean when talking about a model, meta-model, MPS, or others.


== Contact

To contact us join our https://jetbrains-mps.slack.com/archives/C01ADCD6VSM[#modelix Slack channel] which is part of the JetBrains MPS workspace or write us mailto:TODO@TODO.TODO[an Email with your questions and feedback,role=email].


== About this documentation

This is the modelix documentation for modelix version *{page-component-display-version}*.
You can choose different versions at the bottom left of this page.

This documentation is built using the https://antora.org/[Antora] framework.
All individual software components contain their own documentation within their own repository but are aggregated here.
The playbook for aggregation and central source source for this documentation can be found in the https://github.com/modelix/modelix.doc[modelix/modelix.doc] repository.
If you find any bugs or errors in our documentation please add pull requests or issues in the corresponding repository.

